/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_clock.h"
#include "fsl_lpi2c.h"
#include "fsl_lpuart.h"
#include "fsl_semc.h"
#include "fsl_gpio.h"
#include "fsl_gpt.h"
#include "fsl_qtmr.h"
#include "fsl_trng.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* BOARD_InitPeripherals defines for LPI2C4 */
/* Definition of peripheral ID */
#define LPI2C4_PERIPHERAL LPI2C4
/* Definition of clock source */
#define LPI2C4_CLOCK_FREQ 60000000UL
/* Transfer buffer size */
#define LPI2C4_MASTER_BUFFER_SIZE 1
/* Definition of slave address */
#define LPI2C4_MASTER_SLAVE_ADDRESS 0
/* Definition of peripheral ID */
#define LPUART1_PERIPHERAL LPUART1
/* Definition of the clock source frequency */
#define LPUART1_CLOCK_SOURCE 80000000UL
/* BOARD_InitPeripherals defines for SEMC */
/* Definition of peripheral ID. */
#define SEMC_PERIPHERAL SEMC
/* GPIO1 interrupt vector ID (number). */
#define GPIO1_GPIO_COMB_0_15_IRQN GPIO1_Combined_0_15_IRQn
/* GPIO1 interrupt handler identifier. */
#define GPIO1_GPIO_COMB_0_15_IRQHANDLER GPIO1_Combined_0_15_IRQHandler
/* GPIO1 interrupt vector ID (number). */
#define GPIO1_GPIO_COMB_16_31_IRQN GPIO1_Combined_16_31_IRQn
/* GPIO1 interrupt handler identifier. */
#define GPIO1_GPIO_COMB_16_31_IRQHANDLER GPIO1_Combined_16_31_IRQHandler
/* Definition of peripheral ID */
#define GPT1_PERIPHERAL GPT1
/* Definition of the clock source frequency */
#define GPT1_CLOCK_SOURCE 62500000UL
/* BOARD_InitPeripherals defines for LPI2C1 */
/* Definition of peripheral ID */
#define LPI2C1_PERIPHERAL LPI2C1
/* Definition of clock source */
#define LPI2C1_CLOCK_FREQ 60000000UL
/* Transfer buffer size */
#define LPI2C1_MASTER_BUFFER_SIZE 1
/* Definition of slave address */
#define LPI2C1_MASTER_SLAVE_ADDRESS 0
/* Definition of peripheral ID */
#define TMR2_PERIPHERAL TMR2
/* Definition of the timer channel Channel_0. */
#define TMR2_CHANNEL_0_CHANNEL kQTMR_Channel_0
/* Definition of the timer channel Channel_1. */
#define TMR2_CHANNEL_1_CHANNEL kQTMR_Channel_1
/* Definition of the timer channel Channel_0 clock source frequency. */
#define TMR2_CHANNEL_0_CLOCK_SOURCE 976562UL
/* Definition of the timer channel Channel_1 clock source frequency. */
#define TMR2_CHANNEL_1_CLOCK_SOURCE 15UL
/* TMR2 interrupt vector ID (number). */
#define TMR2_IRQN TMR2_IRQn
/* TMR2 interrupt handler identifier. */
#define TMR2_IRQHANDLER TMR2_IRQHandler
/* Definition of peripheral ID */
#define TRNG_PERIPHERAL TRNG

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const lpi2c_master_config_t LPI2C4_masterConfig;
extern lpi2c_master_transfer_t LPI2C4_masterTransfer;
extern uint8_t LPI2C4_masterBuffer[LPI2C4_MASTER_BUFFER_SIZE];
extern lpi2c_master_handle_t LPI2C4_masterHandle;
extern const lpuart_config_t LPUART1_config;
extern semc_config_t SEMC_config;
extern semc_sdram_config_t SEMC_sdram_struct;
extern const gpt_config_t GPT1_config;
extern const lpi2c_master_config_t LPI2C1_masterConfig;
extern lpi2c_master_transfer_t LPI2C1_masterTransfer;
extern uint8_t LPI2C1_masterBuffer[LPI2C1_MASTER_BUFFER_SIZE];
extern lpi2c_master_handle_t LPI2C1_masterHandle;
extern const qtmr_config_t TMR2_Channel_0_config;
extern const qtmr_config_t TMR2_Channel_1_config;
extern const trng_config_t TRNG_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
